services:
  flowise:
    image: flowiseai/flowise
    restart: always
    environment:
      - PORT=${PORT}
    ports:
      - "${PORT}:${PORT}"
    volumes:
      - ~/.flowise:/root/.flowise
    entrypoint: /bin/sh -c "sleep 3; flowise start"
    depends_on:
      - ngrok
    network_mode: "host"


  ngrok:
    image: ngrok/ngrok:latest
    command:
      - "http"
      - "${PORT}"
      - "--domain=${DOMAIN}"
    environment:
      NGROK_AUTHTOKEN: ${NGROK_AUTHTOKEN}
      DOMAIN: ${DOMAIN}
    ports:
      - 4040:4040
    network_mode: "host"